# Generated by Django 4.1.1 on 2022-10-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_remove_livros_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Pessimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Otimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
